name: Release latest version to gcr.io
on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  release-daily-7_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '7.1'
          fetch-depth: 100

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Publish release to gcr.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: ''

          source_image_name: docker.pkg.github.com/flownative/docker-composer/composer
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach/composer
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://eu.gcr.io/v2/

  release-daily-7_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '7.2'
          fetch-depth: 100

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Publish release to gcr.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: ''

          source_image_name: docker.pkg.github.com/flownative/docker-composer/composer
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach/composer
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://eu.gcr.io/v2/

  release-daily-7_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '7.3'
          fetch-depth: 100

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Publish release to gcr.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: ''

          source_image_name: docker.pkg.github.com/flownative/docker-composer/composer
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach/composer
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://eu.gcr.io/v2/

  release-daily-7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '7.4'
          fetch-depth: 100

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Publish release to gcr.io
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          tag_latest: 'yes'

          source_image_name: docker.pkg.github.com/flownative/docker-composer/composer
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: eu.gcr.io/flownative-beach/composer
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_REGISTRY_PASSWORD }}
          target_registry_endpoint: https://eu.gcr.io/v2/
